---
project_name: zgsync
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/zgsync/
    binary: zgsync
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/tukaelu/zgsync.Version={{ .Version }}
      - -X github.com/tukaelu/zgsync.Revision={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: darwin
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github  # Use GitHub Releases release notes
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: tukaelu
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
