coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 3%

ignore:
  - "internal/cli/testhelper/**"
  - "internal/testutil/**"
